# Generated by Django 3.2.5 on 2023-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain_of_interesr', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
                ('college_company', models.CharField(max_length=100)),
            ],
        ),
    ]
