# Generated by Django 3.2.5 on 2023-04-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profiledata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledata',
            old_name='domain_of_interesr',
            new_name='domain_of_interest',
        ),
    ]
