# Generated by Django 3.2.5 on 2023-04-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profiledata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='college_company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='domain_of_interest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
