# Generated by Django 3.2.5 on 2023-04-05 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230405_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
