# Generated by Django 3.2.5 on 2023-04-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230409_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetailsdata',
            name='number',
        ),
    ]
