# Generated by Django 3.2.5 on 2023-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_individualsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualsdata',
            name='image',
            field=models.ImageField(default='media/profile_pics/default.jpeg', upload_to='profile_pics'),
        ),
    ]
