# Generated by Django 3.2.5 on 2023-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='profile_pics/'),
        ),
    ]
