# Generated by Django 3.2.5 on 2023-04-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='domain',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
