# Generated by Django 3.2.5 on 2023-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_blogdata_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='logged_in_author',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
