# Generated by Django 3.2.5 on 2023-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_account_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_image',
            field=models.ImageField(default='profile_pics/default.jpeg', upload_to='profile_pics/'),
        ),
    ]
